# Generated by Django 5.1 on 2024-08-22 10:19

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_remove_location_latitude_remove_location_longitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='description_short',
            new_name='short_description',
        ),
        migrations.RemoveField(
            model_name='location',
            name='description_long',
        ),
        migrations.AddField(
            model_name='location',
            name='long_description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Подробное описание'),
        ),
    ]
