# Generated by Django 5.1 on 2024-08-22 10:24

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_rename_description_short_location_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='long_description',
            field=tinymce.models.HTMLField(blank=True, default='', verbose_name='Подробное описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='short_description',
            field=models.TextField(blank=True, default='', verbose_name='Короткое описание'),
            preserve_default=False,
        ),
    ]
