# Generated by Django 5.1 on 2024-08-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_location_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.DecimalField(decimal_places=14, default=0, max_digits=20, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.DecimalField(decimal_places=14, default=0, max_digits=20, verbose_name='Долгота'),
            preserve_default=False,
        ),
    ]
